# Generated by Django 3.0.3 on 2020-07-15 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pub_date', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=512)),
            ],
        ),
    ]
