# Generated by Django 3.0.3 on 2020-07-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pub_date',
            new_name='embeddings',
        ),
    ]
